version: "2.3"
services:
  web:
    image: go-clean-arch
    container_name: wallet_management_api
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mysql:5.7 
    container_name: go_clean_arch_mysql
    command: mysqld --user=root
    volumes:
      - ./wallet.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=f0W32R1gtc
      - MYSQL_USER=f0W32R1gtc
      - MYSQL_PASSWORD=lwROhOORP0
      - MYSQL_ROOT_PASSWORD=lwROhOORP0
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
